-- ============================================
-- Erweiterte Mitarbeitervertrags-Vorlagen (mit Konto/Gehalt)
-- Vorlagen können im Admin unter Verträge jederzeit gelöscht oder angepasst werden.
-- ============================================

-- Sicherstellen, dass contract_type existiert (falls andere Migration noch nicht gelaufen)
ALTER TABLE contract_templates ADD COLUMN IF NOT EXISTS contract_type TEXT;

-- Bestehende Vorlage "mitarbeiter" um Bank/Gehalt ergänzen
UPDATE contract_templates
SET
  template_text = E'ARBEITSVERTRAG (Muster – bitte anpassen und rechtlich prüfen lassen)\n\nZwischen\n\n{{company_name}}\n{{company_address}}\n{{company_postal_code}} {{company_city}}\nvertreten durch {{represented_by}}\n\n– nachfolgend „Arbeitgeber“ –\n\nund\n\nName: {{employee_name}}\nAdresse: {{employee_address}}\n\n– nachfolgend „Arbeitnehmer/in“ –\n\nwird folgender Arbeitsvertrag geschlossen.\n\n§ 1 Beginn und Probezeit\nDer Arbeitsvertrag beginnt am {{start_date}}. Es gilt eine Probezeit von {{probezeit_monate}} Monaten.\n\n§ 2 Tätigkeit\nDer/die Arbeitnehmer/in wird als {{job_title}} beschäftigt.\n\n§ 3 Arbeitszeit\nDie regelmäßige wöchentliche Arbeitszeit beträgt {{working_hours_week}} Stunden. Es gilt die betriebliche Arbeitszeitregelung.\n\n§ 4 Vergütung\nDie monatliche Bruttovergütung beträgt {{salary_brutto}} € und wird jeweils zum Monatsende gezahlt.\n\n§ 5 Gehaltszahlung / Konto\nDie Vergütung wird auf folgendes Konto des/der Arbeitnehmer/in überwiesen:\nKontoinhaber: {{account_holder}}\nBank: {{bank_name}}\nIBAN: {{employee_iban}}\nBIC: {{employee_bic}}\n\nDer/die Arbeitnehmer/in teilt Änderungen der Bankverbindung unverzüglich schriftlich mit.\n\n§ 6 Urlaub\nAnspruch auf den gesetzlichen Erholungsurlaub (mind. 20 Werktage bei 5-Tage-Woche).\n\n§ 7 Verschwiegenheit und Datenschutz\nVerschwiegenheit über betriebliche Angelegenheiten; Verarbeitung im Einklang mit der DSGVO.\n\n§ 8 Kündigung\nEs gelten die gesetzlichen Kündigungsfristen.\n\n§ 9 Schlussbestimmungen\nÄnderungen bedürfen der Schriftform. Gerichtsstand ist der Sitz des Arbeitgebers.\n\n___________________________ (Ort, Datum)    ___________________________ (Arbeitgeber)\n___________________________ (Arbeitnehmer/in)',
  contract_type = 'employee'
WHERE slug = 'mitarbeiter';

-- Zusätzliche Vorlagen: Minijob, Werkstudent, Teilzeit
INSERT INTO contract_templates (slug, label, template_text, contract_type)
VALUES
(
  'mitarbeiter-minijob',
  'Mitarbeitervertrag Minijob (450 €)',
  E'ARBEITSVERTRAG – GERINGFÜGIGE BESCHÄFTIGUNG (Minijob bis 538,33 €/Monat 2025)\n\n(Muster – bitte anpassen und rechtlich prüfen lassen)\n\nZwischen\n\n{{company_name}}\n{{company_address}}\n{{company_postal_code}} {{company_city}}\nvertreten durch {{represented_by}}\n\n– nachfolgend „Arbeitgeber“ –\n\nund\n\nName: {{employee_name}}\nAdresse: {{employee_address}}\n\n– nachfolgend „Arbeitnehmer/in“ –\n\nwird folgender Arbeitsvertrag geschlossen.\n\n§ 1 Geringfügige Beschäftigung\nEs handelt sich um eine geringfügige Beschäftigung im Sinne von § 8 SGB IV. Die monatliche Bruttovergütung beträgt höchstens 538,33 € (Stand 2025; Anpassung bei gesetzlicher Änderung). Die tatsächliche Vergütung beträgt {{salary_brutto}} € brutto monatlich.\n\n§ 2 Beginn und Tätigkeit\nDer Arbeitsvertrag beginnt am {{start_date}}. Der/die Arbeitnehmer/in wird als {{job_title}} beschäftigt. Die wöchentliche Arbeitszeit beträgt maximal {{working_hours_week}} Stunden.\n\n§ 3 Gehaltszahlung / Konto\nDie Vergütung wird zum Monatsende auf folgendes Konto überwiesen:\nKontoinhaber: {{account_holder}}\nBank: {{bank_name}}\nIBAN: {{employee_iban}}\nBIC: {{employee_bic}}\n\nÄnderungen der Bankverbindung sind unverzüglich schriftlich mitzuteilen.\n\n§ 4 Urlaub\nEs besteht Anspruch auf den gesetzlichen Erholungsurlaub anteilig zur Arbeitszeit.\n\n§ 5 Verschwiegenheit und Datenschutz\nVerschwiegenheit über betriebliche Angelegenheiten; Verarbeitung personenbezogener Daten im Einklang mit der DSGVO.\n\n§ 6 Kündigung\nDas Arbeitsverhältnis kann mit einer Frist von 2 Wochen zum Monatsende gekündigt werden. Während einer Probezeit von {{probezeit_monate}} Monaten kann mit 2 Wochen Frist ohne Einhaltung einer bestimmten Frist gekündigt werden.\n\n§ 7 Schlussbestimmungen\nÄnderungen bedürfen der Schriftform. Gerichtsstand ist der Sitz des Arbeitgebers.\n\n___________________________ (Ort, Datum)    ___________________________ (Arbeitgeber)\n___________________________ (Arbeitnehmer/in)',
  'employee'
),
(
  'mitarbeiter-werkstudent',
  'Mitarbeitervertrag Werkstudent',
  E'ARBEITSVERTRAG – WERKSTUDENT (Muster – bitte anpassen und rechtlich prüfen lassen)\n\nZwischen\n\n{{company_name}}\n{{company_address}}\n{{company_postal_code}} {{company_city}}\nvertreten durch {{represented_by}}\n\n– nachfolgend „Arbeitgeber“ –\n\nund\n\nName: {{employee_name}}\nAdresse: {{employee_address}}\n\n– nachfolgend „Werkstudent/in“ –\n\nwird folgender Arbeitsvertrag geschlossen.\n\n§ 1 Werkstudententätigkeit\nDer/die Arbeitnehmer/in ist ordentlich immatrikuliert und übt die Tätigkeit im Rahmen des Studiums als Werkstudent/in aus. Die wöchentliche Arbeitszeit beträgt während der Vorlesungszeit maximal 20 Stunden, in der vorlesungsfreien Zeit können bis zu {{working_hours_week}} Stunden vereinbart werden.\n\n§ 2 Beginn und Probezeit\nDer Arbeitsvertrag beginnt am {{start_date}}. Es gilt eine Probezeit von {{probezeit_monate}} Monaten.\n\n§ 3 Tätigkeit\nDer/die Werkstudent/in wird als {{job_title}} beschäftigt.\n\n§ 4 Vergütung\nDie monatliche Bruttovergütung beträgt {{salary_brutto}} € und wird jeweils zum Monatsende gezahlt.\n\n§ 5 Gehaltszahlung / Konto\nDie Vergütung wird auf folgendes Konto überwiesen:\nKontoinhaber: {{account_holder}}\nBank: {{bank_name}}\nIBAN: {{employee_iban}}\nBIC: {{employee_bic}}\n\nÄnderungen der Bankverbindung sind unverzüglich schriftlich mitzuteilen.\n\n§ 6 Urlaub\nAnspruch auf den gesetzlichen Erholungsurlaub anteilig zur Arbeitszeit.\n\n§ 7 Verschwiegenheit und Datenschutz\nVerschwiegenheit über betriebliche Angelegenheiten; Verarbeitung im Einklang mit der DSGVO.\n\n§ 8 Kündigung\nEs gelten die gesetzlichen Kündigungsfristen. Während der Probezeit kann mit 2 Wochen Frist gekündigt werden.\n\n§ 9 Schlussbestimmungen\nÄnderungen bedürfen der Schriftform. Gerichtsstand ist der Sitz des Arbeitgebers.\n\n___________________________ (Ort, Datum)    ___________________________ (Arbeitgeber)\n___________________________ (Werkstudent/in)',
  'employee'
),
(
  'mitarbeiter-teilzeit',
  'Mitarbeitervertrag Teilzeit',
  E'ARBEITSVERTRAG – TEILZEITBESCHÄFTIGUNG (Muster – bitte anpassen und rechtlich prüfen lassen)\n\nZwischen\n\n{{company_name}}\n{{company_address}}\n{{company_postal_code}} {{company_city}}\nvertreten durch {{represented_by}}\n\n– nachfolgend „Arbeitgeber“ –\n\nund\n\nName: {{employee_name}}\nAdresse: {{employee_address}}\n\n– nachfolgend „Arbeitnehmer/in“ –\n\nwird folgender Arbeitsvertrag geschlossen.\n\n§ 1 Teilzeit\nDas Arbeitsverhältnis wird in Teilzeit begründet. Die regelmäßige wöchentliche Arbeitszeit beträgt {{working_hours_week}} Stunden. Die Verteilung der Arbeitszeit richtet sich nach der betrieblichen Arbeitszeitregelung.\n\n§ 2 Beginn und Probezeit\nDer Arbeitsvertrag beginnt am {{start_date}}. Es gilt eine Probezeit von {{probezeit_monate}} Monaten.\n\n§ 3 Tätigkeit\nDer/die Arbeitnehmer/in wird als {{job_title}} beschäftigt.\n\n§ 4 Vergütung\nDie monatliche Bruttovergütung beträgt {{salary_brutto}} € (anteilig zur Arbeitszeit) und wird jeweils zum Monatsende gezahlt.\n\n§ 5 Gehaltszahlung / Konto\nDie Vergütung wird auf folgendes Konto des/der Arbeitnehmer/in überwiesen:\nKontoinhaber: {{account_holder}}\nBank: {{bank_name}}\nIBAN: {{employee_iban}}\nBIC: {{employee_bic}}\n\nDer/die Arbeitnehmer/in teilt Änderungen der Bankverbindung unverzüglich schriftlich mit.\n\n§ 6 Urlaub\nAnspruch auf den gesetzlichen Erholungsurlaub anteilig zur Arbeitszeit (mind. 20 Werktage bei 5-Tage-Woche, entsprechend gekürzt).\n\n§ 7 Verschwiegenheit und Datenschutz\nVerschwiegenheit über betriebliche und persönliche Angelegenheiten; Verarbeitung im Einklang mit der DSGVO.\n\n§ 8 Kündigung\nEs gelten die gesetzlichen Kündigungsfristen.\n\n§ 9 Schlussbestimmungen\nÄnderungen und Ergänzungen bedürfen der Schriftform. Gerichtsstand ist der Sitz des Arbeitgebers.\n\n___________________________ (Ort, Datum)    ___________________________ (Arbeitgeber)\n___________________________ (Arbeitnehmer/in)',
  'employee'
)
ON CONFLICT (slug) DO NOTHING;
